In [1]:
import sys
import os

sys.path.append(
    os.path.abspath("..")
)

import pandas as pd

from reusable_code.build_event_features import build_event_features

In [2]:
tesla_event_dataset = pd.read_csv(
    "../data/processed/tesla_event_dataset.csv"
)

In [3]:
event_features = build_event_features(
    tesla_event_dataset
)

event_features

,event_id,event_name,event_type,day_1_abnormal_return,day_3_abnormal_return,day_5_abnormal_return,day_1_absolute_abnormal_return,day_3_absolute_abnormal_return,day_5_absolute_abnormal_return
0,TSLA_001,Q4 2022 Earnings,Earnings,0.337815,22.266805,18.814424,0.337815,22.266805,18.814424
1,TSLA_002,Q1 2023 Earnings,Earnings,-2.001445,-9.948254,-10.863438,2.001445,9.948254,10.863438
2,TSLA_003,Q4 2023 Earnings,Earnings,-0.735693,-12.905195,-9.635181,0.735693,12.905195,9.635181
3,TSLA_004,Q1 2024 Earnings,Earnings,0.664790,19.048465,34.537670,0.664790,19.048465,34.537670
4,TSLA_005,Cybertruck Unveiled,Product Launch,0.901923,-5.345202,-7.457915,0.901923,5.345202,7.457915
5,TSLA_006,Model S Plaid Delivery Event,Product Launch,1.429011,2.301904,0.907980,1.429011,2.301904,0.907980
6,TSLA_007,Tesla Semi Delivery Event,Product Launch,0.073605,-4.307340,-7.049593,0.073605,4.307340,7.049593
7,TSLA_008,Cybertruck Deliveries Begin,Product Launch,-2.056729,-3.963723,-1.986794,2.056729,3.963723,1.986794
8,TSLA_009,Global Vehicle Price Cuts,Pricing Strategy,-1.326771,5.602647,8.251983,1.326771,5.602647,8.251983
9,TSLA_010,Further US Price Cuts,Pricing Strategy,-0.399838,-2.163855,-0.831565,0.399838,2.163855,0.831565
10,TSLA_011,Major Price Reductions Across Key Models,Pricing Strategy,-4.321124,8.184982,11.798452,4.321124,8.184982,11.798452
11,TSLA_012,Battery Day,Technology Announcement,-6.617146,-12.646202,-8.481147,6.617146,12.646202,8.481147
12,TSLA_013,AI Day 2022,Technology Announcement,0.442745,-11.182481,-14.084529,0.442745,11.182481,14.084529
13,TSLA_014,"Robotaxi (""We, Robot"") Event",Technology Announcement,-0.770858,-10.325167,-9.074922,0.770858,10.325167,9.074922
14,TSLA_015,5-for-1 Stock Split Announced,Corporate Action,-2.288935,13.894555,28.703411,2.288935,13.894555,28.703411
15,TSLA_016,3-for-1 Stock Split Announced,Corporate Action,-6.461265,-7.516540,-8.534494,6.461265,7.516540,8.534494
16,TSLA_017,Shareholders Approve Elon Musk Pay Package,Corporate Action,2.720432,4.664806,1.372317,2.720432,4.664806,1.372317
17,TSLA_018,Gigafactory Berlin Opens,Factory Expansion,0.595775,-5.199356,-1.517766,0.595775,5.199356,1.517766
18,TSLA_019,"Gigafactory Texas Opening (""Cyber Rodeo"")",Factory Expansion,-4.881340,2.022510,-8.254801,4.881340,2.022510,8.254801
19,TSLA_020,Mexico Gigafactory Announced,Factory Expansion,-1.045611,-5.851277,-9.257418,1.045611,5.851277,9.257418
20,TSLA_021,Touchscreen Recall (NHTSA),Recall,2.513042,-1.435133,-0.984186,2.513042,1.435133,0.984186
21,TSLA_022,FSD Beta Recall via Software Update,Recall,-4.317697,-4.277582,-2.463008,4.317697,4.277582,2.463008
22,TSLA_023,Autopilot Recall Affecting Over 2 Million Vehi...,Recall,-0.417029,5.420605,5.798085,0.417029,5.420605,5.798085

In [4]:
event_features.shape

(23, 9)

In [5]:
event_features.to_csv(
    "../data/processed/tesla_event_features.csv",
    index=False
)

In [6]:
pd.read_csv(
    "../data/processed/tesla_event_features.csv"
    ).head()

,event_id,event_name,event_type,day_1_abnormal_return,day_3_abnormal_return,day_5_abnormal_return,day_1_absolute_abnormal_return,day_3_absolute_abnormal_return,day_5_absolute_abnormal_return
0,TSLA_001,Q4 2022 Earnings,Earnings,0.337815,22.266805,18.814424,0.337815,22.266805,18.814424
1,TSLA_002,Q1 2023 Earnings,Earnings,-2.001445,-9.948254,-10.863438,2.001445,9.948254,10.863438
2,TSLA_003,Q4 2023 Earnings,Earnings,-0.735693,-12.905195,-9.635181,0.735693,12.905195,9.635181
3,TSLA_004,Q1 2024 Earnings,Earnings,0.664790,19.048465,34.537670,0.664790,19.048465,34.537670
4,TSLA_005,Cybertruck Unveiled,Product Launch,0.901923,-5.345202,-7.457915,0.901923,5.345202,7.457915

In [8]:
from reusable_code.build_pre_event_features import get_pre_event_abnormal_return

In [9]:
import pandas as pd

event_features = pd.read_csv(
    "../data/processed/tesla_event_features.csv"
)

event_dataset = pd.read_csv(
    "../data/processed/tesla_event_dataset.csv"
)

tesla = pd.read_csv(
    "../data/raw/TSLA_stock_2019_2026.csv"
)

spy = pd.read_csv(
    "../data/raw/SPY_stock_2019_2026.csv"
)

In [10]:
tesla["Date"] = pd.to_datetime(tesla["Date"])
spy["Date"] = pd.to_datetime(spy["Date"])

In [11]:
from reusable_code.build_pre_event_features import (
    get_pre_event_abnormal_return,
    build_pre_event_features
)

In [12]:
event_date = pd.to_datetime("2023-01-25")

result = get_pre_event_abnormal_return(
    event_date,
    tesla,
    spy
)

print(result)

8.81945074996695

In [13]:
pre_event_features = build_pre_event_features(
    event_features,
    event_dataset,
    tesla,
    spy
)